### ISSUE TITLE
Company Color Scheme non-required

### ISSUE THREAD

**Issue by ItsZiroy** [Teck-Digital/teckboard#16]
![image](https://user-images.githubusercontent.com/44354000/70846631-76ab0c80-1e5b-11ea-8bdd-38ac261fdbf4.png)
Company Color Scheme ist immernoch required. Muss null erlauben.

**Comment by TPausL** [comment]
kümmere ich mich drum habe schon ne idee wie das geht

**Comment by TPausL** [comment]
Fixed in:
8a3d706a354225d37f725d4e4963da9a0f94c809
