### ISSUE TITLE
DATENBANK AUF SERVER ANPASSEN!!!!

### ISSUE THREAD

**Issue by TPausL** [Teck-Digital/teckboard#17]
- Foreign key für user_boards
- Default für shardrole auf board und company

**Comment by TPausL** [comment]
-resource type für content?

**Comment by ItsZiroy** [comment]
> -resource type für content?

Wie meinst du das?

**Comment by TPausL** [comment]
Ne Spalte mit dem typ Image, PDF, text, etc dass das in der app einfacher geht mit dem anzeigen alternative ist in der app Endung auslesen

**Comment by ItsZiroy** [comment]
Wir können gerne eine Spalte mit dem Typ hinzufügen, damit können wir auch noch nen optionalen Titel bzw. ne Beschreibung hinzufügen. Lest ihr das zurzeit Anhand der Endung ab? @TPausL

**Comment by TPausL** [comment]
ja aktuell wird die endung überprüft, typ spalte wäre aber gut falls mehr dateiformate dazu kommen.
beschreibung für bilder ist schön, aber nicht dringend notwendig, wir müssen das design eh bei bildern und texten unterscheiden habe da aber schon ne idee

**Comment by ItsZiroy** [comment]
Okay. Ich habe dann mal file_type hinzugefügt. Wird dann sowas wie "png", "jpeg" , "txt, etc. drinstehen nehme ich an. @HeinzSama  Wäre glaube ich wichtig zu wissen, für die Speicherung, oder? Findest du wir sollten nen Titel oder einen Namen für die Contents hinzufügen?

**Comment by HeinzSama** [comment]
Ich glaube einen Titel oder ein Name wäre überflüssig.

**Comment by TPausL** [comment]
> Wird dann sowas wie "png", "jpeg" , "txt, etc. drinstehen nehme ich an.

Das wäre überflüssig müßte Image, text, etc sein @ItsZiroy

**Comment by ItsZiroy** [comment]
Okay. Titel finde ich auch unnötig. Wieso Image, text. @TPausL Das ist ja der Typ. Also ich verstehe, was du meinst, aber eigentlich können wir dann auch einfach mit den Endungen arbeiten. Ist ja immernoch nen Unterschied zwischen jpeg und png in der Theorie. Und genauso zwischen Word bzw. Page oder PDF. Dann macht das ja eher weniger Sinn da das Wort "Dokument" reinzuschreiben oder?

**Comment by TPausL** [comment]
Für Dokumente stimmt das aber nen png wird genau so wie ein jpg angezeigt ich sage ja das wäre praktisch aber nicht unbedingt notwendig weil sobald wir zb jfif oder andere bildformate erlauben müssen diese auch im App Code geändert werden steht beim content allerdings Image können alle beliebigen bildformate hochgeladen werden ohne Code Änderung

**Comment by ItsZiroy** [comment]
Ich weiß nicht. Ich habe die Spalte erstmal hinzugefügt. Wir können schauen, was wir damit machen.

**Comment by ItsZiroy** [comment]
Oh und ich meine der Name eines Bildes beginnt immer mit pic-

**Comment by TPausL** [comment]
> Oh und ich meine der Name eines Bildes beginnt immer mit pic-

Oh das habe ich noch garnicht bemerkt dann reicht das ja
