### ISSUE TITLE
RegEx für color_scheme perfektionieren

### ISSUE THREAD

**Issue by Abcde110o** [Teck-Digital/teckboard#5]

**Comment by ItsZiroy** [comment]
Current regex:
![image](https://user-images.githubusercontent.com/44354000/69992008-0cd06000-1549-11ea-8d83-4acfe8d04c85.png)

**Comment by ItsZiroy** [comment]
Möglicherweise weniger copy paste, funktioniert aber trotzdem und limitiert alle Falsch eingaben.
